# Generated by Django 3.2 on 2023-09-11 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_auto_20230911_1659'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
                ALTER TABLE "content"."genre" 
                ADD CONSTRAINT "genre_name_uniq" 
                UNIQUE ("name");
            """,
            reverse_sql='ALTER TABLE "content"."genre" DROP CONSTRAINT genre_name_uniq',
        )
    ]
