# Generated by Django 4.2.5 on 2023-09-13 13:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0005_alter_filmwork_creation_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="filmwork",
            name="creation_date",
            field=models.DateField(blank=True, null=True, verbose_name="Creation date"),
        ),
    ]
