# Generated by Django 4.2.5 on 2023-09-13 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0008_alter_filmwork_rating"),
    ]

    operations = [
        migrations.AlterField(
            model_name="genre",
            name="description",
            field=models.TextField(blank=True, null=True, verbose_name="Description"),
        ),
    ]
