# Generated by Django 4.2.5 on 2023-09-18 13:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("movies", "0009_alter_genre_description"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="genrefilmwork",
            constraint=models.UniqueConstraint(
                models.F("film_work"),
                models.F("genre"),
                name="genre_film_work_film_work_genre_uniq",
            ),
        ),
        migrations.AddConstraint(
            model_name="personfilmwork",
            constraint=models.UniqueConstraint(
                models.F("film_work"),
                models.F("person"),
                models.F("role"),
                name="person_film_work_film_work_person_role_uniq",
            ),
        ),
    ]
